# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gnss.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gnss.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngnss.proto\x12\x16SpaceX.API.Device.Gnss\"\xea\x01\n\x0bMeasurement\x12\x1b\n\x13time_of_validity_ns\x18\x01 \x01(\x03\x12\x41\n\x10satellite_system\x18\x02 \x01(\x0e\x32\'.SpaceX.API.Device.Gnss.SatelliteSystem\x12\x0b\n\x03prn\x18\x03 \x01(\x05\x12\x38\n\x0bpseudorange\x18\x04 \x01(\x0b\x32#.SpaceX.API.Device.Gnss.Pseudorange\x12\x34\n\tephemeris\x18\x05 \x01(\x0b\x32!.SpaceX.API.Device.Gnss.Ephemeris\"E\n\x0bPseudorange\x12\x15\n\rpseudorange_m\x18\x01 \x01(\x01\x12\x1f\n\x17pseudorange_variance_m2\x18\x02 \x01(\x02\"\xee\x01\n\tEphemeris\x12\x38\n\x0csv_data_time\x18\x01 \x01(\x0b\x32\".SpaceX.API.Device.Gnss.SatnavTime\x12\x41\n\x10\x63oordinate_frame\x18\x02 \x01(\x0e\x32\'.SpaceX.API.Device.Gnss.CoordinateFrame\x12\x31\n\x08sv_pos_m\x18\x03 \x01(\x0b\x32\x1f.SpaceX.API.Device.Gnss.Vector3\x12\x31\n\x08sv_vel_m\x18\x04 \x01(\x0b\x32\x1f.SpaceX.API.Device.Gnss.Vector3\"y\n\nSatnavTime\x12\x13\n\x0bweek_number\x18\x01 \x01(\r\x12\x17\n\x0fseconds_of_week\x18\x02 \x01(\x01\x12=\n\x0etime_reference\x18\x03 \x01(\x0e\x32%.SpaceX.API.Device.Gnss.TimeReference\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01*\xa1\x01\n\x0fSatelliteSystem\x12\x0b\n\x07SYS_GPS\x10\x00\x12\x0f\n\x0bSYS_GALILEO\x10\x01\x12\x0f\n\x0bSYS_GLONASS\x10\x02\x12\x0e\n\nSYS_BEIDOU\x10\x03\x12\x0c\n\x08SYS_SBAS\x10\x04\x12\x0c\n\x08SYS_QZSS\x10\x05\x12\r\n\tSYS_IRNSS\x10\x06\x12\x10\n\x0cSYS_STARLINK\x10\x07\x12\x12\n\x0eSYS_STARSHIELD\x10\x08*R\n\rTimeReference\x12\x0c\n\x08TIME_GPS\x10\x00\x12\x10\n\x0cTIME_GALILEO\x10\x01\x12\x0f\n\x0bTIME_BEIDOU\x10\x02\x12\x10\n\x0cTIME_GLONASS\x10\x03*9\n\x0f\x43oordinateFrame\x12\x08\n\x04ITRF\x10\x00\x12\x08\n\x04\x45\x43\x45\x46\x10\x01\x12\x08\n\x04GTRF\x10\x02\x12\x08\n\x04PZ90\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gnss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SATELLITESYSTEM']._serialized_start=755
  _globals['_SATELLITESYSTEM']._serialized_end=916
  _globals['_TIMEREFERENCE']._serialized_start=918
  _globals['_TIMEREFERENCE']._serialized_end=1000
  _globals['_COORDINATEFRAME']._serialized_start=1002
  _globals['_COORDINATEFRAME']._serialized_end=1059
  _globals['_MEASUREMENT']._serialized_start=39
  _globals['_MEASUREMENT']._serialized_end=273
  _globals['_PSEUDORANGE']._serialized_start=275
  _globals['_PSEUDORANGE']._serialized_end=344
  _globals['_EPHEMERIS']._serialized_start=347
  _globals['_EPHEMERIS']._serialized_end=585
  _globals['_SATNAVTIME']._serialized_start=587
  _globals['_SATNAVTIME']._serialized_end=708
  _globals['_VECTOR3']._serialized_start=710
  _globals['_VECTOR3']._serialized_end=752
# @@protoc_insertion_point(module_scope)
