# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x1dSpaceX.API.Satellites.Network*\xa3\x03\n\x11UtDisablementCode\x12\x11\n\rUNKNOWN_STATE\x10\x00\x12\x08\n\x04OKAY\x10\x01\x12\x15\n\x11NO_ACTIVE_ACCOUNT\x10\x02\x12 \n\x1cTOO_FAR_FROM_SERVICE_ADDRESS\x10\x03\x12\x0c\n\x08IN_OCEAN\x10\x04\x12\x13\n\x0f\x42LOCKED_COUNTRY\x10\x06\x12\x1f\n\x1b\x44\x41TA_OVERAGE_SANDBOX_POLICY\x10\x07\x12\x14\n\x10\x43\x45LL_IS_DISABLED\x10\x08\x12\x13\n\x0fROAM_RESTRICTED\x10\n\x12\x14\n\x10UNKNOWN_LOCATION\x10\x0b\x12\x14\n\x10\x41\x43\x43OUNT_DISABLED\x10\x0c\x12\x17\n\x13UNSUPPORTED_VERSION\x10\r\x12\x1e\n\x1aMOVING_TOO_FAST_FOR_POLICY\x10\x0e\x12!\n\x1dUNDER_AVIATION_FLYOVER_LIMITS\x10\x0f\x12\x10\n\x0c\x42LOCKED_AREA\x10\x10\"\x04\x08\x05\x10\x05\"\x04\x08\t\x10\t*\x0fINVALID_COUNTRY*\x12UNLICENSED_COUNTRYb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UTDISABLEMENTCODE']._serialized_start=49
  _globals['_UTDISABLEMENTCODE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
