# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetron.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetron.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10telemetron.proto\x12)SpaceX.API.Telemetron.Public.Integrations*\x85\x01\n\x0fRateLimitReason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08NO_LIMIT\x10\x01\x12\x10\n\x0cPOLICY_LIMIT\x10\x02\x12\x15\n\x11USER_CUSTOM_LIMIT\x10\x03\x12\x11\n\rOVERAGE_LIMIT\x10\x05\"\x04\x08\x04\x10\x04*\x15HIGH_HOURLY_AVG_LIMITb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetron_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATELIMITREASON']._serialized_start=64
  _globals['_RATELIMITREASON']._serialized_end=197
# @@protoc_insertion_point(module_scope)
